### ISSUE TITLE
Error when running the code on Weekly Time Frame

### ISSUE THREAD

**Issue by Suresh-py** [BennyThadikaran/stock-pattern#61] opened 2024-09-01 01:41 UTC
I am getting the below error message when trying to run the code on Weekly Time frame. Can you please look into the issue?

`Microsoft Windows [Version 10.0.22621.4112]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Desktop\stock-pattern-main\src>py init.py --tf weekly

    Enter a number to select a pattern.

    0. ALL  - Scan all patterns
    1: BULL - All Bullish patterns
    2: BEAR - All Bearish patterns
    3. VCPU - Bullish VCP (Volatility Contraction pattern)
    4. VCPD - Bearish VCP
    5. DBOT - Double Bottom (Bullish)
    6. DTOP - Double Top (Bearish)
    7. HNSD - Head and Shoulder
    8. HNSU - Reverse Head and Shoulder
    9. TRNG - Triangles (Symmetrical, Ascending, Descending)
    > 3
Scanning `VCPU` patterns on `weekly`. Press Ctrl - C to exit
 56%|███████████████████████████████████████████▍                                  | 1498/2688 [00:33<00:20, 58.44it/s]C:\Users\Desktop\stock-pattern-main\src\loaders\utils.py:168: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(
Error in Future - scaning patterns
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\concurrent\futures\process.py", line 263, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\stock-pattern-main\src\init.py", line 76, in scan_pattern
    df = loader.get(sym)
         ^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\stock-pattern-main\src\loaders\EODFileLoader.py", line 117, in get
    df = df.resample(self.offset_str).agg(self.ohlc_dict).dropna()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python312\site-packages\pandas\core\generic.py", line 9771, in resample
    return get_resampler(
           ^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python312\site-packages\pandas\core\resample.py", line 2050, in get_resampler
    return tg._get_resampler(obj, kind=kind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python312\site-packages\pandas\core\resample.py", line 2272, in _get_resampler
    raise TypeError(
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Desktop\stock-pattern-main\src\init.py", line 161, in process
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
 56%|███████████████████████████████████████████▌                                  | 1503/2688 [00:34<00:26, 44.02it/s]
No patterns detected

C:\Users\Desktop\stock-pattern-main\src>^A
`

**Comment by BennyThadikaran** [comment] 2024-09-02 04:53
>  TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'

This seems to indicate the `Date` column has an invalid date format or the DataFrame was empty which then defaults to pd.Index instead of pd.DatetimeIndex.

I ran it on NIFTY 500 index stocks and could not find any errors.

There seems to be one offending file since the problem occurred at 1503 of 2688.

If the file was empty it would have been skipped, though i need to test to confirm that. 

Assuming you're using EOD2, 

1. Can you share the watchlist file you're using to scan these stocks. It will help reproduce the error.
2. In EOD2, there is a script - `src/defs/diagnostics.py`. It checks for common errors in the daily files. Can you run it and see if any errors are detected.

**Comment by Suresh-py** [comment] 2024-09-02 05:30
1.Here is the watchlist used
[data.csv](https://github.com/user-attachments/files/16832606/data.csv)
2. No Errors detected by diagnostics.py

P.S I didn't get the above error on Monthly timeframe

**Comment by BennyThadikaran** [comment] 2024-09-02 07:33
The error was caused by modthread.csv

```
2000-12-21,1.0,1.0,1.0,1.0,100,,,
2024-02-14,21.0,21.0,21.0,21.0,61,2.0,30.5,61.0
```
Stock was operational from 1995 to 2000 then there is no data until 2024. I checked on Zerodha Kite and it only has the 2024 data. 

This is not a Stock-Patterns error rather a problem in the EOD2 compilation process. This or some other stock with the same ISIN was suspended in 2000 and the ISIN may have been reassigned to this stock in 2024.

**To correct this,** 
- you can open `modthread.csv` in `src/eod2_data/daily` and remove all the data prior to 2024-02-14 and save the file.
- while running checks, **I found another issue** with sillymonks.csv. Temporarily remove `SILLYMONKS` from your watchlist. I will raise another issue and provide a fix for it.

Once was above actions were taken, I have not seen any other errors on daily or weekly scan.

- I will run a scan to see if any other stocks like `MODTHREAD` exist and post the updates to eod2_data on the weekend.
- `SILLYMONKS` seems like a bug with `csv_loader` i will push a fix once its corrected.

**Comment by Suresh-py** [comment] 2024-09-02 10:27
Thank you

**Comment by BennyThadikaran** [comment] 2024-09-02 14:59
`SILLYMONKS` issue has been fixed. See the latest release. You can add it back to the watchlist.

**Comment by Suresh-py** [comment] 2024-09-02 23:38
Thank you for the updates. Code is working fine now

**Closed** 2024-09-02 23:38 UTC

**Comment by BennyThadikaran** [comment] 2024-09-04 06:57
Upcoming changes to EOD2_DATA discussion - https://github.com/BennyThadikaran/eod2/discussions/175

This relates to the error with `modthread`
