### ISSUE TITLE
Dataframe series truth value error

### ISSUE THREAD

**Issue by Prady04** [BennyThadikaran/stock-pattern#28] opened 2024-05-17 13:17 UTC
steps:
clone repository
install pre-requisites 
configure datapath 
symlist:nse500.csv (attached)

select all patterns and run 
Scanning `ALL` patterns. Press Ctrl - C to exit
 68%|█████████████████████████████████▌               | 342/500 [00:06<00:02, 54.75it/s]
Uncaught Exception
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\process.py", line 263, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Pattern_Clone\stock-pattern\src\init.py", line 87, in scan_pattern     
    result = fn(sym, df, pivots)
             ^^^^^^^^^^^^^^^^^^^
  File "D:\python\Pattern_Clone\stock-pattern\src\utils.py", line 906, in find_double_top
    if is_double_top(a, b, c, d, aVol, cVol, avgBarLength, atr):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Pattern_Clone\stock-pattern\src\utils.py", line 354, in is_double_top  
    c - b < atr * 4
  File "D:\python\Pattern_Clone\stock-pattern\venv\Lib\site-packages\pandas\core\generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
"""

  File "D:\python\Pattern_Clone\stock-pattern\src\init.py", line 436, in <module>
    patterns = process(data, fns)
               ^^^^^^^^^^^^^^^^^^
  File "D:\python\Pattern_Clone\stock-pattern\src\init.py", line 143, in process
    result = future.result()
             ^^^^^^^^^^^^^^^
[n500.csv](https://github.com/BennyThadikaran/stock-pattern/files/15349699/n500.csv)

**Comment by BennyThadikaran** [comment] 2024-05-17 16:12
Your setup is fine.

The error was caused by series being passed to the `is_double_top` function. Could be duplicate index in the DataFrame. I suspect this is the ATR value passed. Since everything else has been checked to make sure its a valid number and not a series.

![Screenshot from 2024-05-17 21-35-36](https://github.com/BennyThadikaran/stock-pattern/assets/19973418/74d92f48-36b0-4a0e-83df-003462fb563d)

I have a copy of Nifty 500 stocks but couldnt reproduce the error with todays updated data. I will try with your list and let you know.

I am just releasing a major update to Stock-Patterns. The documentation is pending. So i will add a check for the ATR and club it with the update. Most likely tomorrow.

**Comment by BennyThadikaran** [comment] 2024-05-18 05:53
I have added a possible fix for this issue. Below is a code illustrating the problem.

```python
import pandas as pd

d = {"col1": [1, 2, 2, 4], "col2": [3, 4, 4, 6]}

# Duplicate index 2 added on purpose
df = pd.DataFrame(d, index=pd.Series([1, 2, 2, 3]))

a = df["col1"].at[2] # results in a pandas Series
print("Before", a)

# Fix
if isinstance(a, pd.Series):
    a = a.iloc[0] # get the first value in the Series
    print("After", a)
```

Once i post the update, you can give it a run and check if the issue is resolved.

**Comment by BennyThadikaran** [comment] 2024-05-18 16:41
Try updating the repo and give it a run. Let me know if you still face the same issue.

**Comment by Prady04** [comment] 2024-05-19 10:48
Did that. Same result.

regards,
Pradeep

**Comment by BennyThadikaran** [comment] 2024-05-19 15:16
I have attached `utils.txt`. Rename this attached file to `utils.py` and replace it in `src/utils.py`

I have added a temporary fix to skip the scan for such stocks. But it will also log some debug info like below.

```
XTZUSDT - a: <class 'float'>, b: <class 'numpy.float64'>, c: <class 'float'>, d: <class 'numpy.float64'>, avol: <class 'float'>, cVol: <class 'float'>, avg: <class 'numpy.float64'>, atr: <class 'numpy.float64'> 
```

Can you run the script and paste the log here. XTZUSDT here is the symbol name. If its possible can you provide me the offending symbols CSV file. That way i can run tests of the file and fix it faster.

[utils.txt](https://github.com/BennyThadikaran/stock-pattern/files/15369860/utils.txt)

**Comment by Prady04** [comment] 2024-05-19 16:53
hi you have removed the csv_loader method. so i assume i need an updated
init,py as well?
following stocks are causing the errors. once i remove these from csv it
works fine

VARROC
VBL
VEDL
WELCORP
WELSPUNLIV
WIPRO
ZENSARTECH
ZYDUSWELL
VMART
VIPIND
TRITURBINE
TIINDIA
THERMAX
TORNTPHARM
TRENT
TV18BRDCST
TANLA
TVSMOTOR
TCS
SBIN
POLICYBZR
PHOENIXLTD

**Comment by BennyThadikaran** [comment] 2024-05-19 17:00
No need to update the init.py. Assuming you have updated to the latest 3.0 version, just download utils.txt. Rename to .py and replace your utils.py and run `init.py`. 

It seems like some of your CSV files have duplicate dates. Normally my code should handle this issue, but clearly i missed something. 

If you're using EOD2 you could try running `diagnostic.py` in EOD2 `/src/defs/diagnostic.py`. That will help detect common issues in files. For now if you can run the scan with utils.py i will have the necessary info to get started on a fix.

**Comment by BennyThadikaran** [comment] 2024-05-19 17:02
Can you send me a sample of one the CSV files causing the problem. That will also help.

**Comment by Prady04** [comment] 2024-05-19 17:31
a few data files

**Comment by BennyThadikaran** [comment] 2024-05-20 10:03
I managed to reproduce the error by adding a duplicate entry to the csv file. The issue was the Close value. It has been fixed for good now in all the find_* functions.

**Comment by Prady04** [comment] 2024-05-20 13:48
Awesome, thanks for the update!

regards,
Pradeep

**Closed** 2024-05-21 04:28 UTC
Labels: bug
